on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v5
      # https://github.com/marketplace/actions/setup-node-js-environment
      - uses: actions/setup-node@v4
      - run: npm ci
      # - name: cleanup
      #   run: |
      #     cd lib
      #     find . -maxdepth 1 -type f ! -name 'db.js' ! -name 'utils.js' -exec rm -f {} +
      #     # public folder
      #     cd ../public
      #     find . -maxdepth 1 -type f -delete
      #     cd svg
      #     find . -maxdepth 1 -name '*.json' ! -name 'spritesheet.json' ! -name 'spritesheet@2x.json' -exec rm {} +
      # # https://github.com/marketplace/actions/copy-push-files-action
      # - uses: GuillaumeFalourd/copy-push-files@v1
      #   with:
      #     source_files: readme.md postcss.config.mjs package.json package-lock.json next.config.mjs license jsconfig.json components.json .gitignore .example.env public prisma lib components app
      #     remote_repository: https://github.com/codabool/stargazer
      #     target_branch: main
      #     access_token: ${{ secrets.TOKEN }}
      #     commit_message: build ${{ toJSON(github.run_number) }} hash ${GITHUB_SHA::7}
